"""empty message

Revision ID: 195be12accae
Revises: afed69654ee8
Create Date: 2022-10-05 17:24:27.753274

"""

# revision identifiers, used by Alembic.
revision = "195be12accae"
down_revision = "afed69654ee8"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
