"""empty message

Revision ID: 2297c2920eb8
Revises: 982b34217925
Create Date: 2022-10-04 13:45:38.019001

"""

# revision identifiers, used by Alembic.
revision = "2297c2920eb8"
down_revision = "982b34217925"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("about_me", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("last_seen", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("location", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("member_since", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("name", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    op.drop_column("users", "member_since")
    op.drop_column("users", "location")
    op.drop_column("users", "last_seen")
    op.drop_column("users", "about_me")
    # ### end Alembic commands ###
