"""empty message

Revision ID: 2bac30da651f
Revises: d8206471f3ab
Create Date: 2022-10-03 17:38:36.086671

"""

# revision identifiers, used by Alembic.
revision = "2bac30da651f"
down_revision = "d8206471f3ab"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
