"""empty message

Revision ID: 609304387388
Revises: dfd3c73426c8
Create Date: 2022-10-04 14:53:00.574768

"""

# revision identifiers, used by Alembic.
revision = "609304387388"
down_revision = "dfd3c73426c8"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
