"""empty message

Revision ID: 8ec36c17c18e
Revises: 5b33dfe7076d
Create Date: 2022-10-05 15:26:17.443757

"""

# revision identifiers, used by Alembic.
revision = "8ec36c17c18e"
down_revision = "5b33dfe7076d"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
