"""empty message

Revision ID: 982b34217925
Revises: d63bcf49ef4c
Create Date: 2022-10-04 12:30:12.296640

"""

# revision identifiers, used by Alembic.
revision = "982b34217925"
down_revision = "d63bcf49ef4c"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
