"""empty message

Revision ID: afed69654ee8
Revises: 8ec36c17c18e
Create Date: 2022-10-05 15:27:02.959873

"""

# revision identifiers, used by Alembic.
revision = "afed69654ee8"
down_revision = "8ec36c17c18e"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
