"""empty message

Revision ID: b39b13885a9b
Revises: 51f80764a2a8
Create Date: 2022-10-05 12:18:25.414144

"""

# revision identifiers, used by Alembic.
revision = "b39b13885a9b"
down_revision = "51f80764a2a8"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
