"""empty message

Revision ID: bd97f41c6786
Revises: 609304387388
Create Date: 2022-10-04 15:16:27.968389

"""

# revision identifiers, used by Alembic.
revision = "bd97f41c6786"
down_revision = "609304387388"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
