"""empty message

Revision ID: d2c4020eff16
Revises: 8f14345d6594
Create Date: 2022-10-06 11:46:50.578817

"""

# revision identifiers, used by Alembic.
revision = "d2c4020eff16"
down_revision = "8f14345d6594"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
