"""empty message

Revision ID: d8206471f3ab
Revises: bac99abe8a58
Create Date: 2022-10-03 17:25:36.443117

"""

# revision identifiers, used by Alembic.
revision = "d8206471f3ab"
down_revision = "bac99abe8a58"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
