"""empty message

Revision ID: dfd3c73426c8
Revises: 2297c2920eb8
Create Date: 2022-10-04 14:15:05.442960

"""

# revision identifiers, used by Alembic.
revision = "dfd3c73426c8"
down_revision = "2297c2920eb8"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
