"""empty message

Revision ID: f936606f1717
Revises: bd97f41c6786
Create Date: 2022-10-04 16:10:02.615823

"""

# revision identifiers, used by Alembic.
revision = "f936606f1717"
down_revision = "bd97f41c6786"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("avatar_hash", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_hash")
    # ### end Alembic commands ###
